### ISSUE TITLE
Convert to rebar?

### ISSUE THREAD

**Issue by jhs** [ocastalabs/CouchDB-XO_Auth#1]
Hi. Thanks very much for your work on this!

I used the previous incarnation, CouchDB-Facebook-Authentication, but I had converted it to rebar. I never sent a merge request, but the commit history is here (it's pretty straightforward). https://github.com/iriscouch/CouchDB-Facebook-Authentication/commits/master

Are you interested in converting this project to rebar? Rebar is becoming standard and ubiquitous in Erlang projects, so it would make this project more idiomatic.

Thoughts? Thanks!

**Comment by jhs** [comment]
Please see my fork to get an idea of what this entails. https://github.com/iriscouch/CouchDB-XO_Auth/commits/master

Notably, it makes the plugin work with build-couchdb, so people can run your code with a single command-line entry.

```
rake plugin="git://github.com/ocastalabs/CouchDB-XO_Auth origin/master"
```

That assumes you want to pull the code in. Let me know if you want a pull request.

**Comment by ocasta** [comment]
rebar sounds like a good idea, particularly as we use build-couchdb. Please raise a pull request and I'll merge in the changes

**Comment by gertcuykens** [comment]
Note that I know very little of erlang but I think rebar is overkill? It would duplicate the number of files? Maybe a rebar or mocks branch but not in master.

**Comment by ocasta** [comment]
We have included rebar in the latest version as it seems to have become an Erlang standard
