### ISSUE TITLE
BrowserID support

### ISSUE THREAD

**Issue by jhs** [ocastalabs/CouchDB-XO_Auth#2]
Hi, again! I wrote a BrowserID plugin that does much the same as this project. (It actually uses some code from the old facebook auth plugin.)

https://github.com/iriscouch/browserid_couchdb

Building an application using it is extremely easy: https://github.com/iriscouch/browserid_couchdb/blob/master/example/page.tmpl.html

Are you interested in merging the BrowserID work into this project? Thanks.

**Comment by ocasta** [comment]
Centralising all these different ways of authenticating within one project makes sense to me as long as the testing overhead doesn't get too much

**Comment by jhs** [comment]
Great. I will begin with some exploration in my own fork and send a pull req when it's more gelled. Closing for now.
