### ISSUE TITLE
 CouchDB 1.3.x

### ISSUE THREAD

**Issue by gertcuykens** [ocastalabs/CouchDB-XO_Auth#3]
[Fri, 30 Mar 2012 01:51:31 GMT] [debug] [<0.4229.0>] request_facebook_graphme_info response={ok,"200",
                                                             [{"Access-Control-Allow-Origin",
                                                               "*"},
                                                              {"Cache-Control",
                                                               "private, no-cache, no-store, must-revalidate"},
                                                              {"Content-Type",
                                                               "text/javascript; charset=UTF-8"},
----snip-----
                                                              {"X-Cnection",
                                                               "close"},
                                                              {"Date",
                                                               "Fri, 30 Mar 2012 01:51:30 GMT"},
                                                              {"Content-Length",
                                                               "50"}],
                                                             "{\"id\":\"100001676421210\",\"username\":\"gert.cuykens\"}"}

[Fri, 30 Mar 2012 01:38:42 GMT] [error] [<0.2598.0>] Uncaught error in HTTP request: {error,undef}

[Fri, 30 Mar 2012 01:38:42 GMT] [info] [<0.2598.0>] Stacktrace: [{couch_view,get_map_view,
                                  [{db,<0.98.0>,<0.99.0>,nil,
                                    <<"1333066879927227">>,<0.101.0>,<0.97.0>,
                                    <0.102.0>,
                                    {db_header,6,5,0,
                                     {16521,{3,1,2233},294},
                                     {16815,4,233},
                                     nil,0,nil,nil,1000},
                                    5,
                                    {btree,<0.97.0>,
                                     {16521,{3,1,2233},294},
                                     #Fun<couch_db_updater.10.55895019>,
                                     #Fun<couch_db_updater.11.100913286>,
                                     #Fun<couch_btree.5.16030487>,
                                     #Fun<couch_db_updater.12.39068440>,
                                     snappy},
                                    {btree,<0.97.0>,
                                     {16815,4,233},
                                     #Fun<couch_db_updater.13.114276184>,
                                     #Fun<couch_db_updater.14.2340873>,
                                     #Fun<couch_btree.5.16030487>,
                                     #Fun<couch_db_updater.15.23651859>,
                                     snappy},
                                    {btree,<0.97.0>,nil,
                                     #Fun<couch_btree.3.22291614>,
                                     #Fun<couch_btree.4.13941471>,
                                     #Fun<couch_btree.5.16030487>,nil,snappy},
                                    5,<<"_users">>,
                                    "/usr/local/var/lib/couchdb/_users.couch",
                                    [#Fun<couch_doc.8.29636382>],
                                    [],nil,
                                    {user_ctx,null,[<<"_admin">>],undefined},
                                    nil,1000,
                                    [before_header,after_header,on_file_open],
                                    [{before_doc_update,
                                      #Fun<couch_users_db.before_doc_update.2>},
                                     {after_doc_read,
                                      #Fun<couch_users_db.after_doc_read.2>},
                                     sys_db,
                                     {user_ctx,
                                      {user_ctx,null,
                                       [<<"_admin">>],
                                       undefined}},
                                     sys_db],
                                    snappy,
                                    #Fun<couch_users_db.before_doc_update.2>,
                                    #Fun<couch_users_db.after_doc_read.2>},
                                   <<"_design/xo_auth">>,<<"xrefbyid">>,nil],
                                  []},
                                 {xo_auth,query_xref_view,3,
                                  [{file,"xo_auth.erl"},{line,186}]},
                                 {xo_auth,check_user_database,2,
                                  [{file,"xo_auth.erl"},{line,48}]},
                                 {fb_auth,handle_facebook_access_token,4,
                                  [{file,"fb_auth.erl"},{line,36}]},
                                 {couch_httpd,handle_request_int,5,[]},
                                 {mochiweb_http,headers,5,[]},
                                 {proc_lib,init_p_do_apply,3,
                                  [{file,"proc_lib.erl"},{line,227}]}]

**Comment by ocasta** [comment]
1.3 has introduced couch_mrview. 

Need to change xo_auth:query_xref_view to mirror the changes made to couch_httpd_oauth:query_oauth_view
