### ISSUE TITLE
Trouble with Couchdb 1.3.1

### ISSUE THREAD

**Issue by sebjameswml** [ocastalabs/CouchDB-XO_Auth#7]
Hi folks,
I've been using your excellent Couchdb plugin for logmykidsoff.com for a while now. I want to upgrade couchdb to v 1.3.1, though I note you have tested the current code only for 1.3.0.
I tried the latest CouchDB-XO_Auth out and can no longer login via either Twitter or Facebook. Couchdb produces an error trace like this:

```
[Mon, 10 Feb 2014 16:03:29 GMT] [error] [<0.17166.0>] Uncaught error in HTTP request: {error,undef}
[Mon, 10 Feb 2014 16:03:29 GMT] [info] [<0.17166.0>] Stacktrace: [{couch_view,get_map_view,
                                   [{db,<0.127.0>,<0.128.0>,nil,
                                     <<"1392034832142846">>,<0.129.0>,
                                     <0.126.0>,<0.130.0>,
                                     {db_header,6,1935,0,
                                      {112154,{40,73,37261},44797},
                                      {112912,113,6197},
                                      nil,0,nil,nil,1000},
                                     1935,
                                     {btree,<0.126.0>,
                                      {112154,{40,73,37261},44797},
                                      #Fun<couch_db_updater.10.55895019>,
                                      #Fun<couch_db_updater.11.100913286>,
                                      #Fun<couch_btree.5.25288484>,
                                      #Fun<couch_db_updater.12.39068440>,
                                      snappy},
                                     {btree,<0.126.0>,
                                      {112912,113,6197},
                                      #Fun<couch_db_updater.13.114276184>,
                                      #Fun<couch_db_updater.14.2340873>,
                                      #Fun<couch_btree.5.25288484>,
                                      #Fun<couch_db_updater.15.23651859>,
                                      snappy},
                                     {btree,<0.126.0>,nil,
                                      #Fun<couch_btree.3.20686015>,
                                      #Fun<couch_btree.4.73514747>,
                                      #Fun<couch_btree.5.25288484>,nil,snappy},
                                     1935,<<"_users">>,
                                     "/usr/local/var/lib/couchdb/_users.couch",
                                     [#Fun<couch_doc.8.106888048>],
                                     [],nil,
                                     {user_ctx,null,[<<"_admin">>],undefined},
                                     nil,1000,
                                     [before_header,after_header,on_file_open],
                                     [{before_doc_update,
                                       #Fun<couch_users_db.before_doc_update.2>},
                                      {after_doc_read,
                                       #Fun<couch_users_db.after_doc_read.2>},
                                      sys_db,
                                      {user_ctx,
                                       {user_ctx,null,
                                        [<<"_admin">>],
                                        undefined}},
                                      nologifmissing,sys_db],
                                     snappy,
                                     #Fun<couch_users_db.before_doc_update.2>,
                                     #Fun<couch_users_db.after_doc_read.2>},
                                    <<"_design/xo_auth">>,<<"xrefbyid">>,nil]},
                                  {xo_auth,query_xref_view,3},
                                  {xo_auth,check_user_database,2},
                                  {xo_auth,determine_username,4},
                                  {xo_auth_fb,create_or_update_user,5},
                                  {xo_auth_fb,handle_fb_req,1},
                                  {couch_httpd,handle_request_int,5},
                                  {mochiweb_http,headers,5}]
[Mon, 10 Feb 2014 16:03:29 GMT] [info] [<0.17166.0>] 31.25.190.168 - - GET /_fb?code=*snip_a_great_long_code* 500
[Mon, 10 Feb 2014 16:03:29 GMT] [error] [<0.17166.0>] httpd 500 error response:
 {"error":"unknown_error","reason":"undef"}

```

This occurs after authenticating externally with facebook.

Something similar occurs with an attempt to login via Twitter:

```
[Mon, 10 Feb 2014 16:10:31 GMT] [info] [<0.17763.0>] 31.25.190.168 - - GET /_twitter 302
[Mon, 10 Feb 2014 16:10:35 GMT] [error] [<0.17783.0>] Uncaught error in HTTP request: {error,undef}
[Mon, 10 Feb 2014 16:10:35 GMT] [info] [<0.17783.0>] Stacktrace: [{couch_view,get_map_view,
                                   [{db,<0.127.0>,<0.128.0>,nil,
                                     <<"1392034832142846">>,<0.129.0>,
                                     <0.126.0>,<0.130.0>,
                                     {db_header,6,1935,0,
                                      {112154,{40,73,37261},44797},
                                      {112912,113,6197},
                                      nil,0,nil,nil,1000},
                                     1935,
                                     {btree,<0.126.0>,
                                      {112154,{40,73,37261},44797},
                                      #Fun<couch_db_updater.10.55895019>,
                                      #Fun<couch_db_updater.11.100913286>,
                                      #Fun<couch_btree.5.25288484>,
                                      #Fun<couch_db_updater.12.39068440>,
                                      snappy},
                                     {btree,<0.126.0>,
                                      {112912,113,6197},
                                      #Fun<couch_db_updater.13.114276184>,
                                      #Fun<couch_db_updater.14.2340873>,
                                      #Fun<couch_btree.5.25288484>,
                                      #Fun<couch_db_updater.15.23651859>,
                                      snappy},
                                     {btree,<0.126.0>,nil,
                                      #Fun<couch_btree.3.20686015>,
                                      #Fun<couch_btree.4.73514747>,
                                      #Fun<couch_btree.5.25288484>,nil,snappy},
                                     1935,<<"_users">>,
                                     "/usr/local/var/lib/couchdb/_users.couch",
                                     [#Fun<couch_doc.8.106888048>],
                                     [],nil,
                                     {user_ctx,null,[<<"_admin">>],undefined},
                                     nil,1000,
                                     [before_header,after_header,on_file_open],
                                     [{before_doc_update,
                                       #Fun<couch_users_db.before_doc_update.2>},
                                      {after_doc_read,
                                       #Fun<couch_users_db.after_doc_read.2>},
                                      sys_db,
                                      {user_ctx,
                                       {user_ctx,null,
                                        [<<"_admin">>],
                                        undefined}},
                                      nologifmissing,sys_db],
                                     snappy,
                                     #Fun<couch_users_db.before_doc_update.2>,
                                     #Fun<couch_users_db.after_doc_read.2>},
                                    <<"_design/xo_auth">>,<<"xrefbyid">>,nil]},
                                  {xo_auth,query_xref_view,3},
                                  {xo_auth,check_user_database,2},
                                  {xo_auth,determine_username,4},
                                  {xo_auth_twitter,create_or_update_user,2},
                                  {xo_auth_twitter,handle_twitter_req,1},
                                  {couch_httpd,handle_request_int,5},
                                  {mochiweb_http,headers,5}]
[Mon, 10 Feb 2014 16:10:35 GMT] [info] [<0.17783.0>] 31.25.190.168 - - GET /_twitter?oauth_token=*snip_token*&oauth_verifier=*snip_verifier* 500
[Mon, 10 Feb 2014 16:10:35 GMT] [error] [<0.17783.0>] httpd 500 error response:
 {"error":"unknown_error","reason":"undef"}
```

Does anything jump out as being obvious?
regards,
Seb

**Comment by sebjameswml** [comment]
Ok, it works; I got confused because my init script wasn't stopping couchdb, so the couchdb I was connecting to was running the wrong plugin.

**Comment by jeffmarshall** [comment]
How did you fix it, exactly? I'm getting this:

```
[error] [<0.1807.0>] Uncaught error in HTTP request: {error,undef}
[info] [<0.1807.0>] Stacktrace: [{xo_auth_fb,handle_fb_req,
                                  [{httpd,
                                    {mochiweb_request,
                                     [#Port<0.3158>,'GET',"/_fb",
                                      {1,1},
                                      {7,
                                       {"host",
                                        {'Host',"api.redacted.com:5984"},
                                        {"connection",
                                         {'Connection',"keep-alive"},
                                         {"accept",
                                          {'Accept',
                                           "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"},
                                          nil,
                                          {"accept-encoding",
                                           {'Accept-Encoding',
                                            "gzip,deflate,sdch"},
                                           nil,
                                           {"accept-language",
                                            {'Accept-Language',
                                             "en-US,en;q=0.8"},
                                            nil,nil}}},
                                         {"cookie",
                                          {'Cookie',
                                           "<redacted>"},
                                          nil,nil}},
                                        {"user-agent",
                                         {'User-Agent',
                                          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36"},
                                         nil,nil}}}]},
                                    "50.152.232.71",'GET',
                                    [<<"_fb">>],
                                    [<<"_fb">>],
                                    {dict,6,16,16,8,80,48,
                                     {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]},
                                     {{[[<<"_design">>|
                                         #Fun<couch_httpd.8.112654683>]],
                                       [[<<"_all_docs">>|
                                         #Fun<couch_httpd.8.112654683>]],
                                       [[<<"_view_cleanup">>|
                                         #Fun<couch_httpd.8.112654683>]],
                                       [],[],[],[],[],
                                       [[<<"_compact">>|
                                         #Fun<couch_httpd.8.112654683>]],
                                       [],[],
                                       [[<<"_temp_view">>|
                                         #Fun<couch_httpd.8.112654683>]],
                                       [[<<"_changes">>|
                                         #Fun<couch_httpd.8.112654683>]],
                                       [],[],[]}}},
                                    {user_ctx,<<"jeff">>,
                                     [<<"_admin">>],
                                     <<"{couch_httpd_auth, cookie_authentication_handler}">>},
                                    undefined,
                                    {dict,7,16,16,8,80,48,
                                     {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]},
                                     {{[],
                                       [[<<"_show">>|
                                         #Fun<couch_httpd.10.112654683>]],
                                       [[<<"_info">>|
                                         #Fun<couch_httpd.10.112654683>],
                                        [<<"_list">>|
                                         #Fun<couch_httpd.10.112654683>]],
                                       [[<<"_update">>|
                                         #Fun<couch_httpd.10.112654683>]],
                                       [],[],[],[],
                                       [[<<"_compact">>|
                                         #Fun<couch_httpd.10.112654683>]],
                                       [[<<"_rewrite">>|
                                         #Fun<couch_httpd.10.112654683>]],
                                       [],[],[],
                                       [[<<"_view">>|
                                         #Fun<couch_httpd.10.112654683>]],
                                       [],[]}}},
                                    {<<"682c14f9d95359a65a1f573a301ad037179bda3cfa962c93847d62640051fc34">>,
                                     false},
                                    #Fun<couch_httpd.6.112654683>,
                                    {dict,16,16,16,8,80,48,
                                     {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]},
                                     {{[[<<"_replicate">>|
                                         #Fun<couch_httpd.6.112654683>],
                                        [<<"_restart">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [[<<"_active_tasks">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [[<<"_fb">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [],
                                       [[<<"_utils">>|
                                         #Fun<couch_httpd.5.112654683>],
                                        [<<"/">>|
                                         #Fun<couch_httpd.5.112654683>],
                                        [<<"_config">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [[<<"_log">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [],
                                       [[<<"_db_updates">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [[<<"_all_dbs">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [],
                                       [[<<"favicon.ico">>|
                                         #Fun<couch_httpd.5.112654683>],
                                        [<<"_stats">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [[<<"_session">>|
                                         #Fun<couch_httpd.6.112654683>],
                                        [<<"_uuids">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [],
                                       [[<<"_plugins">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       [[<<"_oauth">>|
                                         #Fun<couch_httpd.6.112654683>]],
                                       []}}}}],
                                  []},
                                 {couch_httpd,handle_request_int,5,
                                  [{file,"couch_httpd.erl"},{line,318}]},
                                 {mochiweb_http,headers,5,
                                  [{file,"mochiweb_http.erl"},{line,94}]},
                                 {proc_lib,init_p_do_apply,3,
                                  [{file,"proc_lib.erl"},{line,239}]}]
```

**Comment by sebjameswml** [comment]
I had two couchdb program's running simultaneously by mistake, one I killed
the older version of couchdb this problem disappeared for me.

On Thursday, 27 November 2014, Jeff Marshall notifications@github.com
wrote:

> How did you fix it, exactly? I'm getting this:
> 
> [error] [<0.1807.0>] Uncaught error in HTTP request: {error,undef}
> [info] [<0.1807.0>] Stacktrace: [{xo_auth_fb,handle_fb_req,
>                                   [{httpd,
>                                     {mochiweb_request,
>                                      [#Port<0.3158>,'GET',"/_fb",
>                                       {1,1},
>                                       {7,
>                                        {"host",
>                                         {'Host',"api.redacted.com:5984"},
>                                         {"connection",
>                                          {'Connection',"keep-alive"},
>                                          {"accept",
>                                           {'Accept',
>                                            "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8"},
>                                           nil,
>                                           {"accept-encoding",
>                                            {'Accept-Encoding',
>                                             "gzip,deflate,sdch"},
>                                            nil,
>                                            {"accept-language",
>                                             {'Accept-Language',
>                                              "en-US,en;q=0.8"},
>                                             nil,nil}}},
>                                          {"cookie",
>                                           {'Cookie',
>                                            "<redacted>"},
>                                           nil,nil}},
>                                         {"user-agent",
>                                          {'User-Agent',
>                                           "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36"},
>                                          nil,nil}}}]},
>                                     "50.152.232.71",'GET',
>                                     [<<"_fb">>],
>                                     [<<"_fb">>],
>                                     {dict,6,16,16,8,80,48,
>                                      {[],[],[],[],[],[],[],[],[],[],[],[],[],
>                                       [],[],[]},
>                                      {{[[<<"_design">>|
>                                          #Fun<couch_httpd.8.112654683>]],
>                                        [[<<"_all_docs">>|
>                                          #Fun<couch_httpd.8.112654683>]],
>                                        [[<<"_view_cleanup">>|
>                                          #Fun<couch_httpd.8.112654683>]],
>                                        [],[],[],[],[],
>                                        [[<<"_compact">>|
>                                          #Fun<couch_httpd.8.112654683>]],
>                                        [],[],
>                                        [[<<"_temp_view">>|
>                                          #Fun<couch_httpd.8.112654683>]],
>                                        [[<<"_changes">>|
>                                          #Fun<couch_httpd.8.112654683>]],
>                                        [],[],[]}}},
>                                     {user_ctx,<<"jeff">>,
>                                      [<<"_admin">>],
>                                      <<"{couch_httpd_auth, cookie_authentication_handler}">>},
>                                     undefined,
>                                     {dict,7,16,16,8,80,48,
>                                      {[],[],[],[],[],[],[],[],[],[],[],[],[],
>                                       [],[],[]},
>                                      {{[],
>                                        [[<<"_show">>|
>                                          #Fun<couch_httpd.10.112654683>]],
>                                        [[<<"_info">>|
>                                          #Fun<couch_httpd.10.112654683>],
>                                         [<<"_list">>|
>                                          #Fun<couch_httpd.10.112654683>]],
>                                        [[<<"_update">>|
>                                          #Fun<couch_httpd.10.112654683>]],
>                                        [],[],[],[],
>                                        [[<<"_compact">>|
>                                          #Fun<couch_httpd.10.112654683>]],
>                                        [[<<"_rewrite">>|
>                                          #Fun<couch_httpd.10.112654683>]],
>                                        [],[],[],
>                                        [[<<"_view">>|
>                                          #Fun<couch_httpd.10.112654683>]],
>                                        [],[]}}},
>                                     {<<"682c14f9d95359a65a1f573a301ad037179bda3cfa962c93847d62640051fc34">>,
>                                      false},
>                                     #Fun<couch_httpd.6.112654683>,
>                                     {dict,16,16,16,8,80,48,
>                                      {[],[],[],[],[],[],[],[],[],[],[],[],[],
>                                       [],[],[]},
>                                      {{[[<<"_replicate">>|
>                                          #Fun<couch_httpd.6.112654683>],
>                                         [<<"_restart">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [[<<"_active_tasks">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [[<<"_fb">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [],
>                                        [[<<"_utils">>|
>                                          #Fun<couch_httpd.5.112654683>],
>                                         [<<"/">>|
>                                          #Fun<couch_httpd.5.112654683>],
>                                         [<<"_config">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [[<<"_log">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [],
>                                        [[<<"_db_updates">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [[<<"_all_dbs">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [],
>                                        [[<<"favicon.ico">>|
>                                          #Fun<couch_httpd.5.112654683>],
>                                         [<<"_stats">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [[<<"_session">>|
>                                          #Fun<couch_httpd.6.112654683>],
>                                         [<<"_uuids">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [],
>                                        [[<<"_plugins">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        [[<<"_oauth">>|
>                                          #Fun<couch_httpd.6.112654683>]],
>                                        []}}}}],
>                                   []},
>                                  {couch_httpd,handle_request_int,5,
>                                   [{file,"couch_httpd.erl"},{line,318}]},
>                                  {mochiweb_http,headers,5,
>                                   [{file,"mochiweb_http.erl"},{line,94}]},
>                                  {proc_lib,init_p_do_apply,3,
>                                   [{file,"proc_lib.erl"},{line,239}]}]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ocastalabs/CouchDB-XO_Auth/issues/7#issuecomment-64744564
> .

## 

Research Associate in Computational Neuroscience
Adaptive Behaviour Research Group
Dept. of Psychology
